#cloud-config

fs_setup:
   - label: ephemeral0,
     filesystem: ext3
     extra_opts: [ "-E", "nodiscard" ]
     device: ephemeral0
     partition: auto
   - label: ephemeral1,
     filesystem: ext3
     extra_opts: [ "-E", "nodiscard" ]
     device: ephemeral1
     partition: auto

mounts:
 - [ ephemeral0, null ]
 - [ ephemeral1, null ]
 - [ ephemeral0, "/media/ephemeral0", "ext3", "defaults,nobootwait,discard", "0", "2" ]
 - [ ephemeral1, "/media/ephemeral1", "ext3", "defaults,nobootwait,discard", "0", "2" ]
