---
- name: Remove 127.0.1.1 from /etc/hosts
  lineinfile: dest="/etc/hosts"
              regexp="^127.0.1.1"
              line=""
              state=absent
  when: "['development'] | is_in(group_names)"

- name: Increase ulimits
  lineinfile: dest="/etc/security/limits.conf"
              regexp="{{ item }} nofile"
              line="* {{ item }} nofile 65536"
  with_items:
    - soft
    - hard

- name: Set system swappiness
  sysctl: name="vm.swappiness"
          value="0"
          reload=yes
          state=present
